-- =====================================================================
-- CAMPAIGN CREATOR HUB — SCHEMA COMPLETO (facebook_ads_manager)
-- =====================================================================
-- Execute este arquivo no Supabase SQL Editor.
-- Importante: Após rodar, habilite este schema em:
-- Settings > API > Exposed schemas no painel do Supabase.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS facebook_ads_manager;

-- Permissões obrigatórias para o PostgREST (API do Supabase)
GRANT USAGE ON SCHEMA facebook_ads_manager TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA facebook_ads_manager TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA facebook_ads_manager TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA facebook_ads_manager
  GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA facebook_ads_manager
  GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;


-- =====================================================================
-- 1. PROFILES
-- =====================================================================
CREATE TABLE facebook_ads_manager.profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE facebook_ads_manager.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "authenticated_all" ON facebook_ads_manager.profiles
  FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- =====================================================================
-- 2. BUSINESS MANAGERS
-- =====================================================================
CREATE TABLE facebook_ads_manager.business_managers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  business_manager_id TEXT NOT NULL,
  access_token TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE facebook_ads_manager.business_managers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "authenticated_all" ON facebook_ads_manager.business_managers
  FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- =====================================================================
-- 3. AD ACCOUNTS
-- =====================================================================
CREATE TABLE facebook_ads_manager.ad_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_manager_id BIGINT REFERENCES facebook_ads_manager.business_managers(id),
  account_id TEXT NOT NULL,
  account_name TEXT NOT NULL,
  currency TEXT DEFAULT 'BRL',
  timezone_name TEXT DEFAULT 'America/Sao_Paulo',
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

ALTER TABLE facebook_ads_manager.ad_accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "authenticated_all" ON facebook_ads_manager.ad_accounts
  FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- =====================================================================
-- 4. CAMPAIGNS
-- =====================================================================
CREATE TABLE facebook_ads_manager.campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ad_account_id BIGINT REFERENCES facebook_ads_manager.ad_accounts(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  objective TEXT NOT NULL,
  status TEXT DEFAULT 'DRAFT',
  daily_budget BIGINT,
  lifetime_budget BIGINT,
  bid_strategy TEXT DEFAULT 'LOWEST_COST_WITHOUT_CAP',
  start_time TIMESTAMPTZ,
  end_time TIMESTAMPTZ,
  facebook_campaign_id TEXT,
  sync_status TEXT DEFAULT 'pending',
  sync_error TEXT,
  last_synced_at TIMESTAMPTZ,
  budget_type TEXT DEFAULT 'daily',
  special_ad_categories TEXT[] DEFAULT '{}',
  execution_id BIGINT REFERENCES facebook_ads_manager.bulk_executions(id),
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

ALTER TABLE facebook_ads_manager.campaigns ENABLE ROW LEVEL SECURITY;
CREATE POLICY "authenticated_all" ON facebook_ads_manager.campaigns
  FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- =====================================================================
-- 5. AD SETS
-- =====================================================================
CREATE TABLE facebook_ads_manager.ad_sets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id BIGINT REFERENCES facebook_ads_manager.campaigns(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  status TEXT DEFAULT 'DRAFT',
  targeting_countries TEXT[] DEFAULT '{"BR"}',
  age_min INT DEFAULT 18,
  age_max INT DEFAULT 65,
  genders INT[] DEFAULT '{0}',
  daily_budget BIGINT,
  start_time TIMESTAMPTZ,
  end_time TIMESTAMPTZ,
  facebook_adset_id TEXT,
  sync_status TEXT DEFAULT 'pending',
  sync_error TEXT,
  execution_id BIGINT REFERENCES facebook_ads_manager.bulk_executions(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE facebook_ads_manager.ad_sets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "authenticated_all" ON facebook_ads_manager.ad_sets
  FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- =====================================================================
-- 6. ADS
-- =====================================================================
CREATE TABLE facebook_ads_manager.ads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ad_set_id BIGINT REFERENCES facebook_ads_manager.ad_sets(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  status TEXT DEFAULT 'DRAFT',
  headline TEXT,
  primary_text TEXT,
  call_to_action TEXT DEFAULT 'LEARN_MORE',
  link_url TEXT,
  video_drive_url TEXT,
  video_facebook_id TEXT,
  thumbnail_url TEXT,
  facebook_ad_id TEXT,
  sync_status TEXT DEFAULT 'pending',
  sync_error TEXT,
  execution_id BIGINT REFERENCES facebook_ads_manager.bulk_executions(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE facebook_ads_manager.ads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "authenticated_all" ON facebook_ads_manager.ads
  FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- =====================================================================
-- 7. PIXELS
-- =====================================================================
CREATE TABLE facebook_ads_manager.pixels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_manager_id BIGINT REFERENCES facebook_ads_manager.business_managers(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  pixel_id TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE facebook_ads_manager.pixels ENABLE ROW LEVEL SECURITY;
CREATE POLICY "authenticated_all" ON facebook_ads_manager.pixels
  FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- =====================================================================
-- 8. AD PAGES
-- =====================================================================
CREATE TABLE facebook_ads_manager.ad_pages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_manager_id BIGINT REFERENCES facebook_ads_manager.business_managers(id) ON DELETE CASCADE,
  page_id TEXT NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE facebook_ads_manager.ad_pages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "authenticated_all" ON facebook_ads_manager.ad_pages
  FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- =====================================================================
-- 9. INSTAGRAM ACCOUNTS
-- =====================================================================
CREATE TABLE facebook_ads_manager.instagram_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_manager_id BIGINT REFERENCES facebook_ads_manager.business_managers(id) ON DELETE CASCADE,
  ad_page_id BIGINT REFERENCES facebook_ads_manager.ad_pages(id) ON DELETE SET NULL,
  instagram_actor_id TEXT NOT NULL,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE facebook_ads_manager.instagram_accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "authenticated_all" ON facebook_ads_manager.instagram_accounts
  FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- =====================================================================
-- 10. WEBSITES
-- =====================================================================
CREATE TABLE facebook_ads_manager.websites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_manager_id BIGINT REFERENCES facebook_ads_manager.business_managers(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE facebook_ads_manager.websites ENABLE ROW LEVEL SECURITY;
CREATE POLICY "authenticated_all" ON facebook_ads_manager.websites
  FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- =====================================================================
-- 11. BULK TEMPLATES
-- =====================================================================
CREATE TABLE facebook_ads_manager.bulk_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  config JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE facebook_ads_manager.bulk_templates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "authenticated_all" ON facebook_ads_manager.bulk_templates
  FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- =====================================================================
-- 12. BULK EXECUTIONS
-- =====================================================================
CREATE TABLE facebook_ads_manager.bulk_executions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  total_campaigns INT DEFAULT 0,
  total_adsets INT DEFAULT 0,
  total_ads INT DEFAULT 0,
  error_message TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE facebook_ads_manager.bulk_executions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "authenticated_all" ON facebook_ads_manager.bulk_executions
  FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- =====================================================================
-- 13. ADVIDEOS TASKS
-- =====================================================================
CREATE TABLE facebook_ads_manager.advideos_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_drive_id TEXT NOT NULL,
  video_name TEXT,
  meta_video_id TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  execution_id BIGINT REFERENCES facebook_ads_manager.bulk_executions(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE facebook_ads_manager.advideos_tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "authenticated_all" ON facebook_ads_manager.advideos_tasks
  FOR ALL TO authenticated USING (true) WITH CHECK (true);


-- =====================================================================
-- HELPER: Auto-update updated_at
-- =====================================================================
CREATE OR REPLACE FUNCTION facebook_ads_manager.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER profiles_updated_at
  BEFORE UPDATE ON facebook_ads_manager.profiles
  FOR EACH ROW EXECUTE PROCEDURE facebook_ads_manager.handle_updated_at();

CREATE TRIGGER business_managers_updated_at
  BEFORE UPDATE ON facebook_ads_manager.business_managers
  FOR EACH ROW EXECUTE PROCEDURE facebook_ads_manager.handle_updated_at();

CREATE TRIGGER ad_accounts_updated_at
  BEFORE UPDATE ON facebook_ads_manager.ad_accounts
  FOR EACH ROW EXECUTE PROCEDURE facebook_ads_manager.handle_updated_at();

CREATE TRIGGER campaigns_updated_at
  BEFORE UPDATE ON facebook_ads_manager.campaigns
  FOR EACH ROW EXECUTE PROCEDURE facebook_ads_manager.handle_updated_at();

CREATE TRIGGER ad_sets_updated_at
  BEFORE UPDATE ON facebook_ads_manager.ad_sets
  FOR EACH ROW EXECUTE PROCEDURE facebook_ads_manager.handle_updated_at();

CREATE TRIGGER ads_updated_at
  BEFORE UPDATE ON facebook_ads_manager.ads
  FOR EACH ROW EXECUTE PROCEDURE facebook_ads_manager.handle_updated_at();

CREATE TRIGGER pixels_updated_at
  BEFORE UPDATE ON facebook_ads_manager.pixels
  FOR EACH ROW EXECUTE PROCEDURE facebook_ads_manager.handle_updated_at();

CREATE TRIGGER ad_pages_updated_at
  BEFORE UPDATE ON facebook_ads_manager.ad_pages
  FOR EACH ROW EXECUTE PROCEDURE facebook_ads_manager.handle_updated_at();

CREATE TRIGGER instagram_accounts_updated_at
  BEFORE UPDATE ON facebook_ads_manager.instagram_accounts
  FOR EACH ROW EXECUTE PROCEDURE facebook_ads_manager.handle_updated_at();

CREATE TRIGGER websites_updated_at
  BEFORE UPDATE ON facebook_ads_manager.websites
  FOR EACH ROW EXECUTE PROCEDURE facebook_ads_manager.handle_updated_at();

CREATE TRIGGER bulk_templates_updated_at
  BEFORE UPDATE ON facebook_ads_manager.bulk_templates
  FOR EACH ROW EXECUTE PROCEDURE facebook_ads_manager.handle_updated_at();
